spring:
  datasource:
    url: "jdbc:postgresql://localhost:15432/unlock_service"
    username: "your_username"
    password: "your_password"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
